#include "declarations.h"

void initPortA () {
	SYSCTL_RCGCGPIO_R |= 0x01;
	while ((SYSCTL_PRGPIO_R & 0x01)==0) {}
	
	GPIO_PORTA_LOCK_R  = 0x4C4F434B;
	GPIO_PORTA_CR_R    = 0x7F;
	GPIO_PORTA_AFSEL_R = 0x00;
	GPIO_PORTA_PCTL_R = 0x00;
	GPIO_PORTA_AMSEL_R = 0x00;
	GPIO_PORTA_DEN_R = 0x7F;
}

void initPortB () {
	SYSCTL_RCGCGPIO_R |= 0x20;
	while ((SYSCTL_PRGPIO_R & 0x02)==0) {}
	
	GPIO_PORTB_LOCK_R = 0x4C4F434B;
	GPIO_PORTB_CR_R = 0x7F;
	GPIO_PORTB_AFSEL_R = 0x00;
	GPIO_PORTB_PCTL_R = 0x00;
	GPIO_PORTB_AMSEL_R = 0x00;
	GPIO_PORTB_DEN_R = 0x7F;
}

void initPortD () {
	SYSCTL_RCGCGPIO_R |= 0x08;
	while ((SYSCTL_PRGPIO_R & 0x08)==0) {}
	
	GPIO_PORTD_LOCK_R  = 0x4C4F434B;
	GPIO_PORTD_CR_R    = 0x7F;
	GPIO_PORTD_AFSEL_R = 0x00;
	GPIO_PORTD_PCTL_R = 0x00;
	GPIO_PORTD_AMSEL_R = 0x00;
	GPIO_PORTD_DEN_R = 0x7F;
}

void initPortE () {
	SYSCTL_RCGCGPIO_R |= 0x10;
	while ((SYSCTL_PRGPIO_R & 0x10)==0) {}
	
	GPIO_PORTE_LOCK_R  = 0x4C4F434B;
	GPIO_PORTE_CR_R    = 0x2F;
	GPIO_PORTE_AFSEL_R = 0x00;
	GPIO_PORTE_PCTL_R = 0x00;
	GPIO_PORTE_AMSEL_R = 0x00;
	GPIO_PORTE_DEN_R = 0x2F;
}

void initPortF () {
	SYSCTL_RCGCGPIO_R |= 0x20;
	while ((SYSCTL_PRGPIO_R & 0x20)==0) {}
	
	GPIO_PORTF_LOCK_R = 0x4C4F434B;
	GPIO_PORTF_CR_R = 0x1F;
	GPIO_PORTF_AFSEL_R = 0x00;
	GPIO_PORTF_PCTL_R = 0x00;
	GPIO_PORTF_AMSEL_R = 0x00;
	GPIO_PORTF_DIR_R = 0x0E;
	GPIO_PORTF_DEN_R = 0x1F;
	GPIO_PORTF_PUR_R = 0x11;
}


